module.exports = [{
    name: "ALL",
    color: "#2f3542"
}, {
    name: "HTML/CSS/JS",
    color: "#74b9ff"
},{
    name: "JavaScript",
    color: "#F7E017"
}, {
    name: "Jquery",
    color: "#0B67AB"
}, {
    name: "Express.js",
    color: "#FD9326"
}, {
    name: "TypeScript",
    color: "#007ACD"
}, {
    name: "Socket.io",
    color: "#b2bec3"
}, {
    name: "Node.js",
    color: "#80BC01"
}, {
    name: "MongoDB",
    color: "#81C764"
}, {
    name: "Mongoose",
    color: "#880002"
}, {
    name: "HTML5/Canvas",
    color: "#EF6026"
}, {
    name: "Vue.js",
    color: "#02C180"
}, {
    name: "Vuetify",
    color: "#1976d2"
}, {
    name: "React.js",
    color: "#4AD5FE"
}, {
    name: "Kotlin",
    color: "#7E70E4"
}, {
    name: "Swift",
    color: "#F05237"
}, {
    name: "Java",
    color: "#E77002"
}, {
    name: "C++",
    color: "#014383"
}, {
    name: "Python",
    color: "#2A6EB2"
},{
    name: "MariaDB",
    color: "#A67444"
}]